services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /usr/local/nginx/html:/usr/share/nginx/html
      - /usr/local/nginx/logs:/var/log/nginx
      - /usr/local/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx/conf.d:/etc/nginx/conf.d

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "password"
    volumes:
      - /usr/local/minio/database:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090" --address ":9000"


volumes:
  mysql_data:
  redis_data: